[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
md5 = "0.7.0"
serde = "1.0.145"
serde_derive = "1.0.145"
serde_scan = "0.4.1"
